words = [
    "breakindent",
    "bufnr",
    "bufremove",
    "cmdline",
    "commandbar",
    "commentstring",
    "condit",
    "cterm",
    "diffopt",
    "diffview",
    "dropbar",
    "editmsg",
    "enew",
    "eob",
    "fillchars",
    "fixendofline",
    "foldclose",
    "foldcolumn",
    "foldenable",
    "foldexpr",
    "foldlevel",
    "foldmethod",
    "foldopen",
    "formatoptions",
    "gitcommit",
    "grepprg",
    "guicursor",
    "guifont",
    "gzip",
    "hilink",
    "hipatterns",
    "ignorecase",
    "indentscope",
    "keymaps",
    "laststatus",
    "lazydev",
    "lefta",
    "lspconfig",
    "lsps",
    "luvit",
    "mapleader",
    "matchit",
    "matchparen",
    "minideps",
    "miniindentscope",
    "ministarter",
    "navbuddy",
    "neovide",
    "netrw",
    "nofile",
    "numberwidth",
    "pmenu",
    "qall",
    "sbar",
    "scrolloff",
    "shiftwidth",
    "showmode",
    "signcolumn",
    "smartcase",
    "sourcekit",
    "spellfile",
    "splitbelow",
    "splitkeep",
    "splitright",
    "startify",
    "statusline",
    "tabstop",
    "termguicolors",
    "themefile",
    "timeoutlen",
    "topline",
    "trunc",
    "undofile",
    "undotree",
    "unnamedplus",
    "updatetime",
    "vimball",
    "wildignore",
    "wildignorecase",
    "wildoptions",
    "winborder",
    "yazi",
]
