words = [
    "checkboxes",
    "csharpier",
    "cwd",
    "deno",
    "formatters",
    "gpt",
    "graphiti",
    "hsl",
    "latexindent",
    "mcp",
    "neovim",
    "nvim",
    "opencode",
    "ripgrep",
    "selenized",
    "strikethrough",
    "stylua",
    "undercurl",
    "wez",
    "wezterm",
]
