words = [
    "aapl",
    "altool",
    "bikeshed",
    "checkboxes",
    "csharpier",
    "cwd",
    "deno",
    "eaddrinuse",
    "etf",
    "formatters",
    "gpt",
    "graphiti",
    "hono",
    "hsl",
    "iphonesimulator",
    "kysely",
    "latexindent",
    "linters",
    "mcp",
    "mkdir",
    "moneyscope",
    "neovim",
    "nvim",
    "nyt",
    "oneline",
    "opencode",
    "osascript",
    "pangrams",
    "plists",
    "ripgrep",
    "segoe",
    "selenized",
    "setuid",
    "simctl",
    "strawman",
    "strikethrough",
    "stylua",
    "subagents",
    "udid",
    "undercurl",
    "updateable",
    "wez",
    "wezterm",
    "wss",
    "xcconfig",
    "xcodebuild",
    "xcodeproj",
    "xcrun",
    "zod",
]
