[metadata]
name = 'Catppuccin Mocha (catppuccin)'

[colors]
ansi = [
	'#45475a',
	'#f38ba8',
	'#a6e3a1',
	'#f9e2af',
	'#89b4fa',
	'#f5c2e7',
	'#94e2d5',
	'#bac2de',
]
background = '#1e1e2e'
brights = [
	'#585b70',
	'#f38ba8',
	'#a6e3a1',
	'#f9e2af',
	'#89b4fa',
	'#f5c2e7',
	'#94e2d5',
	'#a6adc8',
]
compose_cursor = '#f2cdcd'
cursor_bg = '#f5e0dc'
cursor_border = '#f5e0dc'
cursor_fg = '#11111b'
foreground = '#cdd6f4'
scrollbar_thumb = '#585b70'
selection_bg = '#585b70'
selection_fg = '#cdd6f4'
split = '#6c7086'
visual_bell = '#313244'

[colors.indexed]
16 = '#fab387'
17 = '#f5e0dc'
18 = '#cba6f7'
19 = '#b4befe'

[colors.tab_bar]
background = '#45475a'

[colors.tab_bar.active_tab]
bg_color = '#1e1e2e'
fg_color = '#cdd6f4'

[colors.tab_bar.inactive_tab]
bg_color = '#313244'
fg_color = '#a6adc8'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#585b70'
fg_color = '#cdd6f4'

[colors.tab_bar.new_tab]
bg_color = '#45475a'
fg_color = '#45475a'

[colors.tab_bar.new_tab_hover]
bg_color = '#45475a'
fg_color = '#cdd6f4'
